### ISSUE TITLE
Scaling for  10" Model

### ISSUE THREAD

**Issue by DrSKiZZ** [anthonycaccese/es-theme-picade#2]
How does this scale for the 10" model as this looks like it was made for the 8" screen.

**Comment by anthonycaccese** [comment]
Hi @DrSKiZZ you are right i did test and build this on the 8" version.  Just looking at the pimoroni site now I see the 10" doesn't have a bezel so its possible that the background lines won't match up but sadly I don't have a 10" model to test on.  That said looking at the resolution of the 10" its the same @ 1024x768 so I would expect the rest of the theme to scale correctly.

**Comment by michelegera** [comment]
Can confirm that on the 10" lines do not align, but it’s not a huge deal IMO. Rest of the theme scales perfectly 👍 

![picade-theme](https://user-images.githubusercontent.com/3891/107932396-cdd7d000-6f7d-11eb-9ef2-e31bef64cb46.jpg)

**Comment by anthonycaccese** [comment]
Thank you for checking and glad it looks ok even though the background doesn’t line up like the 8in screen.
